Exception: Failure "test".
Raised at Stdlib.failwith in file "stdlib.ml", line 34, characters 17-33
Called from <unknown> in file "pr9701.ml", line 5, characters 9-16
Called from Topeval.load_lambda in file "ocaml/toplevel/byte/topeval.ml", line 90, characters 4-14
